## Setting eureka
eureka:
  instance:
    preferIpAddress: true                           # Register the IP of the service rather than the server name
  client:
    registerWithEureka: true                        # Register the service with Eureka
    fetchRegistry: true                             # Pull down a local copy of the registry
    serviceUrl:
        defaultZone: http://localhost:8761/eureka/

## Setting logging levels
logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.thoughtmechanix: DEBUG

## Setting security
security:
  oauth2:
    resource:
      userInfoUri: http://localhost:8901/auth/user  # url to validate the access token

## Setting server
server:
  port: 8060                                        # port of service

## Setting Message queue
spring:
  cloud:
    stream:
      bindings:
        output:
          destination:  orgChangeTopic              # The name of message queue
          content-type: application/json            # The type of messages are going to be sent and received
        kafka:
          binder:
             zkNodes: localhost                     # The location of ZooKeeper
             brokers: localhost                     # The location of message broker (Kafka)