## Setting spring
spring:
  application:
    name: zipkinserver             # name of service

## Setting logging levels
logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.thoughtmechanix: DEBUG

## Setting server
server:
  port: 9411                       # The port of service
